[flake]
backend = "rust-crane"

[ci]
runtime = "nix"
runner = "ubuntu-24.04"
with_nextest = true
with_audit = true
with_deny = true
with_docs = true
provider = "actions"
platform = "github"
workspace = true

[ci.pages]
repo = "caniko/nix-article"
canonical_domain = "nix-article.tartanoglu.com"
