name: CI

on:
  push:
    branches: [trunk]

jobs:
  checks:
    runs-on: atlas-nix-trusted
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run flake checks
        run: nix flake check

  test:
    runs-on: atlas
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build anx CLI
        run: cargo build --package anx

      - name: Run Rust tests
        run: cargo test --package anx

      - name: Run Python tests
        working-directory: python
        run: uv sync --frozen && uv run pytest

  docs:
    runs-on: atlas-nix-trusted
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build docs
        run: nix build .#docs
