"""Centralised sizing constants for manuscript figures.

Single source of truth shared between Python figure generation and LaTeX.
Run ``anx sizes sync`` to regenerate LaTeX size/font files.

Design
------
Figures are drawn at exactly ``\\linewidth`` so that LaTeX includes them
at native resolution with **zero scaling** (scale = 1.0).  Font sizes
in matplotlib are the final *printed* sizes.
"""

from __future__ import annotations

from pathlib import Path

# ── Page geometry (A4 default) ────────────────────────────────────────
PAGE_WIDTH_MM: float = 210
PAGE_HEIGHT_MM: float = 297
MARGIN_MM: float = 25

# Derived
LINEWIDTH_MM: float = PAGE_WIDTH_MM - 2 * MARGIN_MM
TEXTHEIGHT_MM: float = PAGE_HEIGHT_MM - 2 * MARGIN_MM
LINEWIDTH_IN: float = LINEWIDTH_MM / 25.4
TEXTHEIGHT_IN: float = TEXTHEIGHT_MM / 25.4

# ── Canvas size ───────────────────────────────────────────────────────
FIGWIDTH_IN: float = LINEWIDTH_IN
SCALE: float = 1.0

# Reserve ~31 mm (6 baselines at 11pt) for caption + label + skip
_CAPTION_RESERVE_MM: float = 31.0
MAX_FIG_HEIGHT_IN: float = (TEXTHEIGHT_MM - _CAPTION_RESERVE_MM) / 25.4

# ── Resolution ────────────────────────────────────────────────────────
DPI_SAVE = 300
DPI_DISPLAY = 150

# ── Font families ─────────────────────────────────────────────────────
FONT_MAIN = "Latin Modern Roman"
FONT_SANS = "Latin Modern Sans"
FONT_MONO = "Latin Modern Mono"
# Matplotlib fallback chain when Latin Modern is unavailable
FONT_SANS_FALLBACK: list[str] = ["LM Sans 10", "Inter", "Helvetica", "Arial"]

# ── Font sizes (pt) — final printed sizes, no pre-scaling ─────────────
FONT_SMALL: float = 7.0
FONT_BASE: float = 8.0
FONT_LABEL_AXIS: float = 9.0
FONT_BIG: float = 10.0
FONT_PANEL: float = 14.0

# Aliases for rcParams
FONT_TICK: float = FONT_SMALL
FONT_LEGEND: float = FONT_SMALL
FONT_AXIS_LABEL: float = FONT_LABEL_AXIS
FONT_AXIS_TITLE: float = FONT_BIG

# ── Shared subplot adjust defaults ────────────────────────────────────
SUBPLOT_ADJUST = dict(top=0.94, bottom=0.04, left=0.08, right=0.98)


def constrained_figsize(
    n_rows: int,
    row_height_in: float = 2.5,
    hspace_frac: float = 0.15,
) -> tuple[float, float]:
    """Compute a figsize that fits within a single A4 page."""
    raw_height = n_rows * row_height_in * (1 + hspace_frac)
    clamped = min(raw_height, MAX_FIG_HEIGHT_IN)
    return (FIGWIDTH_IN, round(clamped, 2))


_LEADING_FACTOR = 1.2


def _fontsize_cmd(name: str, pt: float) -> str:
    bl = pt * _LEADING_FACTOR
    return rf"\newcommand{{\{name}}}{{\fontsize{{{pt:g}}}{{{bl:g}}}\selectfont}}"


def generate_latex_fonts(output_path: Path | str) -> None:
    """Write ``fonts.tex`` — shared font sizes for TikZ panels.

    Defines ``\\synSmall`` … ``\\synTitle`` macros matching Python
    ``FONT_*`` constants, plus shared TikZ styles (``syndb``, ``synbox``,
    ``synarr``, ``synlbl``).
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    macros = "\n".join(
        [
            _fontsize_cmd("synSmall", FONT_SMALL),
            _fontsize_cmd("synBase", FONT_BASE),
            _fontsize_cmd("synLabel", FONT_LABEL_AXIS),
            _fontsize_cmd("synTitle", FONT_BIG),
        ]
    )

    output_path.write_text(
        "% Auto-generated by anx_plot.sizing — do not edit.\n"
        "% Regenerate with: anx sizes sync\n"
        "%\n"
        f"% Font families (shared with matplotlib):\n"
        f"%   main = {FONT_MAIN}\n"
        f"%   sans = {FONT_SANS}\n"
        f"%   mono = {FONT_MONO}\n"
        "%\n"
        r"\ifdefined\synfontsloaded\endinput\fi"
        "\n"
        r"\def\synfontsloaded{1}"
        "\n"
        "\n"
        r"% ── Font families (requires fontspec) ──────────────────────────────"
        "\n"
        r"\ifdefined\setmainfont"
        "\n"
        f"  \\setmainfont{{{FONT_MAIN}}}\n"
        f"  \\setsansfont{{{FONT_SANS}}}\n"
        f"  \\setmonofont{{{FONT_MONO}}}\n"
        r"\fi"
        "\n"
        "\n"
        "% Font size macros — matches FONT_* in sizing.py.\n"
        "% Size macros are pure \\fontsize switches (no family).\n"
        "% Use the synbox/synarr/synlbl TikZ styles to apply sffamily.\n"
        "%\n"
        f"% FONT_SMALL  = {FONT_SMALL:g} pt  ->  \\synSmall\n"
        f"% FONT_BASE   = {FONT_BASE:g} pt  ->  \\synBase\n"
        f"% FONT_LABEL  = {FONT_LABEL_AXIS:g} pt  ->  \\synLabel\n"
        f"% FONT_BIG    = {FONT_BIG:g} pt  ->  \\synTitle\n"
        "\n"
        f"{macros}\n"
        "\n"
        r"% ── Shared TikZ styles ────────────────────────────────────────────"
        "\n"
        r"\AtBeginDocument{%"
        "\n"
        r"  \ifdefined\tikzset"
        "\n"
        r"  \tikzset{"
        "\n"
        r"    syndb/.style={"
        "\n"
        r"      >=Stealth,"
        "\n"
        r"      every node/.append style={"
        "\n"
        r"        font=\synBase,"
        "\n"
        r"        execute at begin node={\sffamily},"
        "\n"
        r"      },"
        "\n"
        r"    },"
        "\n"
        r"    synbox/.style={"
        "\n"
        r"      draw=pal-dark, rounded corners=2pt, minimum height=8mm,"
        "\n"
        r"      text=white, font=\synBase\bfseries, align=center,"
        "\n"
        r"    },"
        "\n"
        r"    synarr/.style={"
        "\n"
        r"      ->, color=pal-dark!60, line width=0.6pt,"
        "\n"
        r"    },"
        "\n"
        r"    synlbl/.style={"
        "\n"
        r"      font=\synSmall, fill=white, inner sep=1.5pt,"
        "\n"
        r"      rounded corners=1pt,"
        "\n"
        r"    },"
        "\n"
        r"  }%"
        "\n"
        r"  \fi"
        "\n"
        r"}"
        "\n",
        encoding="utf-8",
    )


def generate_latex_sizes(output_path: Path | str) -> None:
    """Write ``figure_sizes.tex`` so LaTeX stays in sync with Python.

    Sets ``\\setkeys{Gin}`` defaults that match Python figure dimensions,
    and defines ``\\maxfigheight`` as a safety guard.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "% Auto-generated by anx_plot.sizing — do not edit.\n"
        "% Regenerate with: anx sizes sync\n"
        f"% Page: {PAGE_WIDTH_MM}x{PAGE_HEIGHT_MM} mm, margins {MARGIN_MM} mm\n"
        f"% linewidth = {LINEWIDTH_MM:.0f} mm  ~ {LINEWIDTH_IN:.2f} in\n"
        f"% textheight = {TEXTHEIGHT_MM:.0f} mm  ~ {TEXTHEIGHT_IN:.2f} in\n"
        f"% Canvas width = {FIGWIDTH_IN:.1f} in, scale factor ~ {SCALE:.3f}\n"
        f"% Max figure height = {MAX_FIG_HEIGHT_IN:.2f} in\n"
        f"% DPI = {DPI_SAVE}\n"
        "\\setkeys{Gin}{width=\\linewidth,keepaspectratio}\n"
        "\\newlength{\\maxfigheight}\n"
        "\\setlength{\\maxfigheight}{\\dimexpr\\textheight-6\\baselineskip\\relax}\n",
        encoding="utf-8",
    )
