[book]
title = "anx — Article Toolchain"
authors = ["caniko"]
language = "en"
src = "src"

[output.html]
smart-punctuation = true
no-section-label = true
site-url = "/docs/"
git-repository-url = "https://codeberg.org/caniko/nix-article"
edit-url-template = "https://codeberg.org/caniko/nix-article/edit/main/docs/src/{path}"
